### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ultravu** [colossatr0n/HiRes-Amazon-Shirt-Downloader#1]
hello colossatr0n, I tried to run your code but it returned this error: IndexError: list index out of range
 "![Screenshot 2022-05-09 152826](https://user-images.githubusercontent.com/105201383/167370965-10e1d6ac-383f-4ebd-9063-3c64e3c01103.jpg)"
 any ideas how to solve this? thank you!

**Comment by colossatr0n** [comment]
Hello @ultravu ,

I apologize for getting back to you so late. Make sure to supply the URL of the page that has the images.

`python AmazonHiResDownloader.py www.someamazonurl.com`
